[#21] Connected Android module with naver webtoon.
deNsuh/toonDra pull request #24
Opened 2016-10-08 18:16 UTC by harry2636

Fixes #21 

- Able to crawl the Naver Webtoon Content including main webtoons, best challenge webtoons and challenge webtoons.
- Able to query the webtoon infos from the Android application.

2016-10-09 15:13 UTC, dansuh17 requested changes

2016-10-09 15:13 UTC, deNsuh commented on Android/toonDra/app/src/main/AndroidManifest.xml
unnecessary blank line

2016-10-09 15:15 UTC, deNsuh commented
just to make sure - this is only an import of files for webtoon crawling, right? no representation on mainactivity yet?

2016-10-09 15:46 UTC, harry2636 commented on Android/toonDra/app/src/main/AndroidManifest.xml
Fixed it.

2016-10-09 15:48 UTC, harry2636 commented
@deNsuh Yes, it is. there is no representation on main activity yet. Code for main activity will be committed in another pull request.

Fixed requested points.

2016-10-10 03:23 UTC, deNsuh commented
LGTM

2016-10-11 12:20 UTC, heewoonam commented
LGTM

2016-10-11 12:20 UTC, merged