[#25] Implemented dashboard page with preview mode and gridView mode.
deNsuh/toonDra pull request #32
Opened 2016-11-14 03:31 UTC by harry2636

Fixes #25 

- Queries thumbnail images and first episode previews form the server.
- Get webtoon infos categorized by days.
- Able to convert preview mode to gridView mode with button on the menu.
- Add sample webtoon list view page and read page.

2016-11-18 12:04 UTC, dansuh17 reviewed
review by me

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/PreviewModeFragment.java
> +    View view = inflater.inflate(R.layout.previewmode_fragment_main, container, false );
space before `)`?

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/PreviewModeFragment.java
> +
unnecessary blank line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/PreviewModeFragment.java
> +
unnecessary blank line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/PreviewModeFragment.java
> +          for (Element imgLink : wtViewer.children()) {
I get `NullPointerException` here. It seems that we need to handle the case where the page does not have DOM element having class `wt_viewer`.
How about adding a catch statement?

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/ReadEpisodePage.java
> +
unnecessary blank line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/ReadEpisodePage.java
> +
UBL (unnecessary blank line)

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/layout/episode_read_page.xml
> +</FrameLayout>
end of file with no extra line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/layout/episodelist_fragment.xml
> +</LinearLayout>
end of file with no blank line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/layout/gridviewmode_fragment_main.xml
> +</LinearLayout>
EOF with no extra line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/layout/page_custom.xml
> +/>
EOF with no blank line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/layout/previewmode_fragment_main.xml
> +</LinearLayout>
EOF with no extra line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/layout/thumbnail_custom.xml
> +</LinearLayout>
EOF with no extra line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/menu/activity_main_drawer.xml
> +</menu>
EOF with no extra line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/res/menu/main.xml
> +</menu>
EOF with no extra line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/App.java
> +}
EOF with no extra line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/EpisodeListPage.java
> +
unnecessary blank line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/GridViewModeFragment.java
> +
unnecessary blank line

2016-11-18 12:04 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/MainActivity.java
> +
unnecessary blank lines

2016-11-18 12:07 UTC, deNsuh commented
Also, I get OoM (Out of Memory) Exception. I presume that this is due to large image file sizes. We have two options : 1. increase the heap size of JVM, 2. resize image files [see here](http://stackoverflow.com/questions/10413659/how-to-resize-image-in-android)

2016-11-18 13:24 UTC, harry2636 commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/PreviewModeFragment.java
> +          for (Element imgLink : wtViewer.children()) {
I think NullPointerException only occurs when the user accesses the 19 years old webtoon. (It is blocked due to permission problem.) I will put alert message for this.

2016-11-18 14:02 UTC, harry2636 commented
@deNsuh Can you explain the situation where the OOM occurs? Does it occurs in read episode page?

2016-11-18 14:16 UTC, deNsuh commented
@harry2636 Yes it occurs within the read episode. It rarely happens immediately after entering the view, but while scrolling.

2016-11-18 14:27 UTC, heewoonam requested changes
Null pointer exception when there is no Internet connection.

2016-11-18 15:53 UTC, harry2636 commented
@deNsuh @heewoonam 
I fixed all null pointer exception cases.
For the read page OOM, it occurs because the current read page uses "res/drawable" files. After I implement the read page with the remote server, the OOM bug will be automatically fixed.
I just commented the sample read page parts.

2016-11-18 17:36 UTC, deNsuh commented on Android/toonDra/app/src/main/res/drawable/thumb_back.xml
> +</shape>
one last empty line before EOF 😉 
LGTM except this.

2016-11-18 17:37 UTC, deNsuh commented
LGTM, except for the one thing commented above :)

2016-11-20 11:10 UTC, harry2636 commented
All done, I will merge it, because @heewoonam said that he is busy so that we can merge the commit.

2016-11-20 11:10 UTC, merged