[#26][#33] Implement scrolling with blinking + handle.
deNsuh/toonDra pull request #34
Opened 2016-11-19 09:06 UTC by deNsuh

Implements #26 
Fixes #33 

**Implements scrolling with blinking**

* Each blink is detected and adjusts scrolling speed.
* Also added a handler to the main UI thread so that FaceTracker thread could send message and modify indirectly the UI components.
* Further calibration on scrolling algorithm needed.

2016-11-20 11:25 UTC, harry2636 commented
LGTM. Looks great!

2016-11-27 19:18 UTC, heewoonam requested changes

2016-11-27 19:18 UTC, heewoonam commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/AutoscrollActivity.java
> +    countDownTimer = new CountDownTimer(MILLIS_IN_FUTURE / Math.abs(scrollVelocity),
Divide by zero error

2016-11-27 19:18 UTC, heewoonam commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/AutoscrollActivity.java
> +  private TextView textarea;
textarea -> textArea would be better?

2016-11-27 19:20 UTC, heewoonam commented
Scrolling accuracy is very bad... Doesn't seem to recognize blinking well enough I guess. Scroll speed varies a lot every time even though when I'm blinking just once

2016-12-02 14:47 UTC, dansuh17 commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/AutoscrollActivity.java
> +    countDownTimer = new CountDownTimer(MILLIS_IN_FUTURE / Math.abs(scrollVelocity),
done

2016-12-02 14:47 UTC, deNsuh commented on Android/toonDra/app/src/main/java/edu/kaist/mskers/toondra/AutoscrollActivity.java
> +  private TextView textarea;
done

2016-12-02 14:48 UTC, deNsuh commented
@heewoonam We'll leave those tasks to future issues :)

2016-12-02 14:48 UTC, merged